name: Interim Village
favicon: null
layout_spectrum: 0.5297256743069738
typography_spectrum: 0.6831724606454372
title: Community for Interim Managers and Executives
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6492164216469973
  lightness: 0.3089429575484246
  saturation: 0.24873671191744506
  rhythmicContrast: 0.1937659925315529
purpose: []
